export enum NotificationType {
  // Space
  CREATE_SPACE = 'CREATED_SPACE',
  UPDATE_SPACE = 'UPDATED_SPACE',
  DELETE_SPACE = 'DELETED_SPACE',
  YOU_WERE_REMOVED_FROM_SPACE = 'YOU_WERE_REMOVED_FROM_SPACE',

  // Space Member
  ADD_MEMBER_TO_SPACE = 'ADDED_MEMBER_TO_SPACE',
  REMOVE_MEMBER_FROM_SPACE = 'REMOVED_MEMBER_FROM_SPACE',
  YOU_WERE_ADDED_TO_SPACE = 'YOU_WERE_ADDED_TO_SPACE',

  // Project
  CREATE_PROJECT = 'CREATED_PROJECT',
  UPDATE_PROJECT = 'UPDATED_PROJECT',
  DELETE_PROJECT = 'DELETED_PROJECT',
  YOU_WERE_REMOVED_FROM_PROJECT = 'YOU_WERE_REMOVED_FROM_PROJECT',

  // Project Member
  ADD_MEMBER_TO_PROJECT = 'ADDED_MEMBER_TO_PROJECT',
  REMOVE_MEMBER_FROM_PROJECT = 'REMOVED_MEMBER_FROM_PROJECT',
  YOU_WERE_ADDED_TO_PROJECT = 'YOU_WERE_ADDED_TO_PROJECT',

  // Task
  CREATE_TASK = 'CREATED_TASK',
  UPDATE_TASK = 'UPDATED_TASK',
  DELETE_TASK = 'DELETED_TASK',
  YOU_WERE_ASSIGNED_TASK = 'YOU_WERE_ASSIGNED_TASK',
  TASK_STATUS_CHANGED = 'TASK_STATUS_CHANGED',
  TASK_PENDING_APPROVAL = 'TASK_PENDING_APPROVAL',
  TASK_APPROVED = 'TASK_APPROVED',
  TASK_REJECTED = 'TASK_REJECTED',
}
